- name: Deploy Cacti Tray Mobile
  hosts: appserver
  tasks:
    - include_tasks: ./tasks/install_packages.yml
    - include_tasks: ./tasks/upload_app_src.yml
    - include_tasks: ./tasks/install_vendors.yml
    - include_tasks: ./tasks/run_migrations.yml
