- name: Preparing installation
  block:
    - name: Check composer is installed
      stat:
        path: /usr/local/bin/composer
      register: composer_here
  
    - name: Install composer
      ansible.builtin.shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      when: not composer_here.stat.exists
